
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.ConnectionProvider;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author anuradha
 */
public class Billing extends javax.swing.JFrame {

    int count = 0;
    

    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c_name = new javax.swing.JTextField();
        c_no = new javax.swing.JTextField();
        c_dr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        exp = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Add = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Total = new javax.swing.JButton();
        total_price = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        c_pay_type = new javax.swing.JComboBox<>();
        Print = new javax.swing.JButton();
        quantity = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.PNG"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1271, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Curlz MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText(" CodeOn Pharmacy");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 286, -1));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel2.setText(" Billing ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Customer Details");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel5.setText("MobileNo :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel6.setText("Ref by Dr. :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        c_name.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        c_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nameActionPerformed(evt);
            }
        });
        getContentPane().add(c_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 200, -1));

        c_no.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        getContentPane().add(c_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 200, -1));

        c_dr.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        getContentPane().add(c_dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 200, -1));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel7.setText("Medicine");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel8.setText("Exp_date :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel9.setText("Stock :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel10.setText("Medicine_Id :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel11.setText("Name :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));

        exp.setEditable(false);
        exp.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        getContentPane().add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 220, 190, -1));

        name.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 204, -1));

        id.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 204, -1));

        Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Table.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Medicine_Id", "Medicine_Name", "Exp_date", "Mfg_date", "Supplier", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.setRowHeight(30);
        Table.setRowMargin(5);
        Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setResizable(false);
            Table.getColumnModel().getColumn(1).setResizable(false);
            Table.getColumnModel().getColumn(2).setResizable(false);
            Table.getColumnModel().getColumn(3).setResizable(false);
            Table.getColumnModel().getColumn(4).setResizable(false);
            Table.getColumnModel().getColumn(5).setResizable(false);
            Table.getColumnModel().getColumn(6).setResizable(false);
            Table.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 1060, 190));

        Add.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, -1, -1));

        Clear.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 410, -1, -1));

        Search.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        Total.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        Total.setText("Total");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 690, 150, -1));

        total_price.setEditable(false);
        total_price.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        total_price.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_price.setText("0");
        getContentPane().add(total_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 690, 150, -1));

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel13.setText("Payment_Type :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        c_pay_type.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        c_pay_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Upi", "Netbanking" }));
        c_pay_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_pay_typeActionPerformed(evt);
            }
        });
        getContentPane().add(c_pay_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 200, -1));

        Print.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        getContentPane().add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 620, -1, -1));

        quantity.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 350, 190, 40));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel14.setText("Price :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 190, 40));

        Home.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel15.setText("Quantity :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 350, 190, 40));

        price.setEditable(false);
        price.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 200, -1));

        stock.setEditable(false);
        stock.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 290, 190, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jackie-matthews-photography-6079016_1920.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, -30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nameActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:

        String Id = id.getText();
        String Name = name.getText();
        int Quantity = (int) quantity.getValue();
        int Stock = Integer.valueOf(stock.getText());
        String Exp = exp.getText();
        String Mfg;
        String Supplier;
        float Price;

        if ("".equals(Id) || "".equals(Name) || "".equals(Exp)) {
            JOptionPane.showMessageDialog(null, "medicine_id or name require");

        } else {
            if (Stock < Quantity || Quantity == 0) {
                JOptionPane.showMessageDialog(null, "stock is less or quantity selected is 0");

            } else {
                Connection con = null;
                java.sql.Statement st = null;
                try {

                    con = ConnectionProvider.getCon();
                    st = con.createStatement();
                    ResultSet rs = null;

                    rs = st.executeQuery("select * from medicines where medicine_id='" + Id + "' or medicine_name='" + Name + "';");

                    while (rs.next()) {

                        Id = rs.getString("medicine_id");
                        Name = rs.getString("medicine_name");
                        Exp = rs.getString("exp_date");
                        Mfg = rs.getString("mfg_date");
                        Supplier = rs.getString("supplier");
                        Price = rs.getFloat("medicine_price");

                        Quantity = (int) quantity.getValue();

                        count += 1;

                        Object row[] = {count, Id, Name, Exp, Mfg, Supplier, Price, Quantity};
                        DefaultTableModel model = (DefaultTableModel) Table.getModel();

                        model.addRow(row);
                        JOptionPane.showMessageDialog(null, "added");

                    }

                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                } finally {
                    try {
                        con.close();
                        st.close();
                    } catch (SQLException e) {

                    }
                }
            }

        }


    }//GEN-LAST:event_AddActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:++
        int count = 0;
        float total = 0;
        count = Table.getRowCount();
        count--;
        while (count >= 0) {
            float value1 = (float) Table.getValueAt(count, 6);
            int value2 = (int) Table.getValueAt(count, 7);

            total = total + value1 * value2;
            count--;
        }
        total_price.setText(String.valueOf(total));


    }//GEN-LAST:event_TotalActionPerformed

    private void c_pay_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_pay_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_pay_typeActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        id.setText("");
        exp.setText("");
        name.setText("");
        stock.setText("");
        price.setText("");
        quantity.setValue(0);

    }//GEN-LAST:event_ClearActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String Id = id.getText();
        String Name = name.getText();
        String Exp;
        float Price;
        int Stock = 0;

        if ("".equals(Id) && "".equals(Name)) {
            JOptionPane.showMessageDialog(null, "medicine_id or name require");
        } else {
            Connection con = null;
            java.sql.Statement st = null;
            try {

                con = ConnectionProvider.getCon();
                st = con.createStatement();
                ResultSet rs = null;

                rs = st.executeQuery("select * from medicines where medicine_id='" + Id + "' or medicine_name='" + Name + "';");

                while (rs.next()) {
                    Id = rs.getString("medicine_id");
                    Name = rs.getString("medicine_name");
                    Exp = rs.getString("exp_date");
                    Price = rs.getFloat("medicine_price");

                    id.setText(Id);
                    name.setText(Name);
                    exp.setText(Exp);
                    price.setText(String.valueOf(Price));

                }

                rs = st.executeQuery("select * from medicine_stock where medicine_id= '" + Id + "';");
                while (rs.next()) {
                    Stock = rs.getInt("quantity");
                    stock.setText(String.valueOf(Stock));

                }

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                try {
                    con.close();
                    st.close();
                } catch (SQLException e) {

                }
            }

        }
    }//GEN-LAST:event_SearchActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        int cusid = 0;
        String Name =null;
        String Customer_Name = c_name.getText();
        String Customer_Number = c_no.getText();
        String Customer_Dr = c_dr.getText();
        Object PayType = c_pay_type.getSelectedItem();
        float Total = Float.valueOf(total_price.getText());
        String Id;
        int Stock = 0;
        int Quantity = 0;
        Date obj = new Date();
        String date = obj.toString();

        Connection con = null;
        java.sql.Statement st = null;
        try {

            con = ConnectionProvider.getCon();
            st = con.createStatement();
            ResultSet rs = null;

            if ("".equals(Customer_Name) || "".equals(Customer_Number) || Total == 0 || "".equals(Customer_Dr) || PayType == "") {
                JOptionPane.showMessageDialog(null, "Customer Details Require or total is zero");
            } else {
                
                exp.setVisible(false);
                price.setVisible(false);
                stock.setVisible(false);
                quantity.setVisible(false);
                Clear.setVisible(false);
                Add.setVisible(false);
                Search.setVisible(false);
                Home.setVisible(false);
                Print.setVisible(false);
                jLabel7.setVisible(false);
                jLabel9.setVisible(false);

                jLabel8.setVisible(false);
                jLabel14.setVisible(false);
                jLabel15.setVisible(false);
                Exit.setVisible(false);
                
                Font font1 = new Font("SansSerif", Font.BOLD, 12);
                name.setFont(font1);
                jLabel11.setText("Date :");
                name.setText(date);
                
                jLabel10.setText("Customer_Id :");

                st.executeUpdate("insert into customers values(null,'" + Customer_Name + "','" + Customer_Number + "','" + Total + "','" + Customer_Dr + "','" + PayType + "','" + date + "');");
                rs = st.executeQuery("select * from customers where bill_date='"+date+"';");
                while (rs.next()) {
                    cusid =rs.getInt("Customer_Id");
                    String s = String.valueOf(cusid);
                    id.setText(s);
                }

                PrinterJob job = PrinterJob.getPrinterJob();
                job.setJobName("Printing bill");

                job.setPrintable(new Printable() {
                    public int print(Graphics pg, PageFormat pf, int pageNum) {
                        pf.setOrientation(PageFormat.LANDSCAPE);
                        if (pageNum > 0) {
                            return Printable.NO_SUCH_PAGE;
                        }

                        Graphics2D g2 = (Graphics2D) pg;
                        g2.translate(pf.getImageableX(), pf.getImageableY());
                        g2.scale(0.5, 0.5);

                        paint(g2);
//          

                        return Printable.PAGE_EXISTS;

                    }
                });

                boolean ok = job.printDialog();
                if (ok) {
                    try {

                        job.print();
                    } catch (PrinterException ex) {
                    }
                }

                for (int i = 0; i < Table.getRowCount(); i++) {

                    Id = (String) Table.getValueAt(i, 1);
                    Name=(String) Table.getValueAt(i,2);

                    Quantity = (int) Table.getValueAt(i, 7);

                    rs = st.executeQuery("select * from medicine_stock where medicine_id='" + Id + "'; ");
                    while (rs.next()) {
                        Stock = rs.getInt("quantity");
                        
                    
                    }

                    st.executeUpdate("update  medicine_stock set quantity='" + (Stock - Quantity) + "' where medicine_id='" + Id + "'; ");
                    st.executeUpdate("insert into bill values('"+cusid+"','"+Id+"','"+Name+"','"+Quantity+"');");
                    

                }
                    setVisible(false);
                    JOptionPane.showMessageDialog(null, "Bill printed");
                    new Billing().setVisible(true);
            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                con.close();
                st.close();
            } catch (SQLException e) {

            }
        }


    }//GEN-LAST:event_PrintActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home_page().setVisible(true);
        
          
    }//GEN-LAST:event_HomeActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    /**
     * // * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Home;
    private javax.swing.JButton Print;
    private javax.swing.JButton Search;
    private javax.swing.JTable Table;
    private javax.swing.JButton Total;
    private javax.swing.JTextField c_dr;
    private javax.swing.JTextField c_name;
    private javax.swing.JTextField c_no;
    private javax.swing.JComboBox<String> c_pay_type;
    private javax.swing.JTextField exp;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JSpinner quantity;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField total_price;
    // End of variables declaration//GEN-END:variables
}
